### PR TITLE
Layout autoresize

### PR DESCRIPTION
**Pull request by dddomodossola**
Can someone test this new feature? Please feedback.

### CODE REVIEW

**Comment by nzjrs** [comment]
How much of this could be achieved by using ```width:100%``` in non-containers?

In other words is all this work necessary because everything has hard coded sizes instead of inheriting what they can inherit from their parents in the HTML?

**Comment by dddomodossola** [comment]
Yes, this is necessary because of the hardcoded size. Are you thinking about removing layout control?

**Comment by nzjrs** [comment]
I'm not really thinking of removing it, just trying to think if it is
necessary in evey widget

**Comment by dddomodossola** [comment]
Mixing sizes in "%" and in "px" can have negative effects. The "exception" have to be managed in the library layouting functions. Furthermore, inheriting size from parents, the children in a container will have the same size.

**Comment by dddomodossola** [comment]
Hi John, following the discussion we got about the Container class you would like to make, do you think that I can merge these changes? Or it is better to add autoresize capabilities only to Containers?

**Comment by nzjrs** [comment]
I would not merge this yet, I think it is better left to containers.

I think non container widgets could have expand properties, which could translate into width=100% or width=parent-margin, if the widget is inside a container.

I think it needs more thought.

**Pull request closed without merging**
