### PR TITLE
Use ephemeral for websockets

### PR DESCRIPTION
**Pull request by nzjrs**
first step to completely configurable port allocation, and thus multiple instance support

### CODE REVIEW

**Comment by dddomodossola** [comment]
John, it is better to have a "preferred" port definition in the configuration.py. And a flag to allow the "autosearch" port. In this way, if I would like to start a script on a defined port on my server I'm able to define this.

**Comment by nzjrs** [comment]
Having configuration globals in a random py file is not going in the direction of making remi a true importable module.

However in this specific case, why would anyone want to care about the websocket port? it is only ever a private implementation detail between the servers.

**Comment by dddomodossola** [comment]
>However in this specific case, why would anyone want to care about the websocket port? it is only ever a private implementation detail between the servers.

Ok on this point, it is not usefull to have a preferred websocket port. However I suppose that in the future we can allow websockets connections as it is like an API export. Different scripts could communicate by websockets calls. However right now could be ok as you suggest.
 

>Having configuration globals in a random py file is not going in the direction of making remi a true importable module.

Can you explain better this?

**Comment by nzjrs** [comment]
>> Having configuration globals in a random py file is not going in the direction of making remi a true >> importable module.

> Can you explain better this?

Currently if I want to use remi in my application I must copy gui.py, server.py and configuration.py into my source tree.

In future, when remi is a true module and can be used like ```from remi import Widget``` how am I expected to configure it?

```python
import remi
remi.configuration.SOMETHING=4

from remi.gui import App
from remi.server import start

class Bla(App): pass

start(Bla)
```

changing global configuration constants before import is very dirty and unpythonic

**Comment by dddomodossola** [comment]
Ok intresting. So, how you plan to do this?

**Comment by nzjrs** [comment]
> Ok intresting. So, how you plan to do this?

all configuration information goes via the Server object and is passed or set in the handlers if necessary

I am working on that here

https://github.com/nzjrs/gui/commits/multiple-instance

**Comment by dddomodossola** [comment]
It seems to be a very good solution.

**Pull request merged**
